### ISSUE TITLE
"Enter Grade" should be a button like "Upload Annotated file"

### ISSUE THREAD

**Issue by jetej** [mitodl/edx-sga#15]
Or vice versa.

But I prefer buttons in this case.

(See https://github.com/jazkarta/edx-sga/issues/18)

**Comment by pdpinch** [comment]
We'll have to update the screen shots in the documentation after this change is made as well.

**Comment by amir-qayyum-arbisoft** [comment]
I have added style to <a> tag to make it look like button (Image is attached). I am not able to replace <a> tag with input button. Because <a> tag is bind with leanModal when i tried to bind it with input button it didnt work.
![a link](https://cloud.githubusercontent.com/assets/10431250/6733165/2b466430-ce72-11e4-9d01-70eafa6eac98.png)

**Comment by pdpinch** [comment]
fixed via #68
