### ISSUE TITLE
"Download all Grades" zip file is empty

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#209]
Testing at https://mitx-qa-next.mitx.mit.edu/courses/course-v1:TestX+Ginkgo101+2018_Spring/courseware/d25bc249694c42ea9306b41d5dab1f93/bda58d0d42ac4c57bf485533e6975de4/2

I can successfully download a zip file, but it's only 102 bytes long and it appears to be empty.

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops @blarghmatey can some one send me s3 settings for my local edx, to reproduce this issue, is there any exception logged in system?

**Comment by amir-qayyum-khan** [comment]
@pdpinch i tested it with S3 settings that @blarghmatey provided me 
and it is working fine. I am able to download zip file. zip file can gave small size because of lesser data, can you extract it and see if those files are there?

cc @mitodl/devops any tips to reproduce it. Can it be file permission issue at path `/edx/app/edxapp/data/{course_id}`?

**Comment by pdpinch** [comment]
I can’t unzip the file. I’ll send you an example.

**Comment by amir-qayyum-khan** [comment]
ok, thanks
