### ISSUE TITLE
Release 0.12.0 is breaking tests at edX

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#281]
@awais786 pinned the prior version to address it in https://github.com/edx/edx-platform/pull/25316 and idenftied the issue as being this test: https://build.testeng.edx.org/job/edx-platform-python-pipeline-pr/22508/testReport/junit/lms.djangoapps.grades.tests.integration.test_problems/TestMultipleProblemTypesSubsectionScores/Run_Tests___lms_unit___test_score_submission_for_all_problems/

```Error Message

AssertionError: 15.0 != 17.0

Stacktrace

self = <lms.djangoapps.grades.tests.integration.test_problems.TestMultipleProblemTypesSubsectionScores testMethod=test_score_submission_for_all_problems>

    def test_score_submission_for_all_problems(self):
        subsection_factory = SubsectionGradeFactory(
            self.student,
            course_structure=self.course_structure,
            course=self.course,
        )
        score = subsection_factory.create(self.seq1)
    
        self.assertEqual(score.all_total.earned, 0.0)
>       self.assertEqual(score.all_total.possible, self.ACTUAL_TOTAL_POSSIBLE)
E       AssertionError: 15.0 != 17.0

lms/djangoapps/grades/tests/integration/test_problems.py:82: AssertionError```

**Comment by asadiqbal08** [comment]
PR -- https://github.com/mitodl/edx-sga/pull/282

#### FINDINGS

We have to update the definition of `parse_xml` in SGA xBlock because xBlock runtime module has a method declaration `add_node_as_child` that is called by XBlock.parse_xml to treat a child node as a child block.
[Reference Code](https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/xblock/runtime/runtime.py#L202-L207)

Update the method definition of parse_xml in SGA xblock that was removed in [PR#270](https://github.com/mitodl/edx-sga/pull/270/files#diff-52fbfd5003bb036038e11d03721c4253R168)
