### ISSUE TITLE
TinyMCE problem in edx-sga problems: `modern` theme not found

### ISSUE THREAD

**Issue by angellareo** [mitodl/edx-sga#346]
When creating a new Staff Graded Assignment problem, the WYSIWIG editor is not showing:
![image](https://github.com/mitodl/edx-sga/assets/2606279/d8b43265-37b9-4e77-aa34-1a14ca752be6)

It seems that the problem comes from getting a 404 Not Found when retrieving
`/static/studio//js/vendor/tinymce/js/tinymce/themes/modern/theme.js`, which in fact does not exist.

Which does exist is `js/tinymce/themes/silver/theme.js` (note that the path refers to a `silver` theme instead of `modern). According to [this github issue](https://github.com/tinymce/tinymce/issues/5015), modern theme was replaced with silver in version 5.

Although there is no reference to tinymce in edx-sga xblock, other problem types such as ORA self-assessment work just great (loading the correct theme):
![image](https://github.com/mitodl/edx-sga/assets/2606279/e97ecf58-5660-43dc-999f-7fe367a6502c)

TinyMCE was upgraded from v4 to v5 in this PR: https://github.com/openedx/edx-platform/pull/30335

The bug might comes from `edx-platform/common/static/js/vendor/tinymce/js/tinymce/jquery.tinymce.min.js`:

`"&themes="+escape(o.theme||"modern")`

We’re at Palm version, deployed with tutor. We’ve been searching how to update the reference to use the TinyMCE silver theme, but with no luck until now.

I've [also posted in Discuss about this issue](https://discuss.openedx.org/t/tinymce-problem-in-edx-sga-problems-modern-theme-not-found/11148), which has been reproduced on the Open edX demo platform.

**Comment by Anas12091101** [comment]
his issue in the Palm release is due to the versions of `Xblock` and `xblock-utils`, which are `1.6.2` and `3.0.0`, respectively. These versions use the `modern theme` for TinyMCE and don't support v5. A possible solution for this problem is to upgrade these versions in the edx-platform `Palm` release by cherry-picking the commits for the upgradation of Xblock and xblock-utils from later releases, such as `quince` or `master`.

**Comment by Anas12091101** [comment]
Hi @angellareo,

Here's an update on this issue:

I received a [comment](https://github.com/openedx/edx-platform/pull/34149#issuecomment-1961829053) from the edX team regarding my PR, stating that there won't be a future edx-platform Palm release. Consequently, this issue will persist in the Palm release. One potential solution for this problem is to upgrade the xblock-utils version in your locally set up edx-platform Palm release to 3.2.0. Alternatively, you could upgrade your edx-platform to the quince release, where TinyMCE v5 is functioning properly.

@pdpinch, we can now close this issue.

**Comment by arslanashraf7** [comment]
@Anas12091101 We have had some version updates of xblock related packages lately. Is it time to circle back on this and see if there is a fix available now?

Otherwise, We should check if `Palm` release should support TinyMCE v5 and if we should create an upstream PR for that? @pdpinch

**Comment by Anas12091101** [comment]
The [PR](https://github.com/openedx/edx-platform/pull/34149) has been merged in edx-platform palm release. We can now close this issue

**Comment by arslanashraf7** [comment]
@angellareo We have got the fix merged into [open-release/palm.master](https://github.com/openedx/edx-platform/tree/open-release/palm.master) release of Open edX, You must pull the latest palm release to get the fix. Please don't hesitate to let us know if you see any issues.

**Comment by dtjchen** [comment]
this is an issue with edx and the tinymce editor:

_forums_: https://discuss.openedx.org/t/tinymce-problem-in-edx-sga-problems-modern-theme-not-found/11148/2

_related issue in a xblock that also uses the field_: https://github.com/mitodl/edx-sga/issues/346

the editor might be improperly initialized in the edx code using a non-existent theme because of a version upgrade

this seems to be recently resolved by them in the `palm` version of edx

---

that being said, i'm assuming we're not performing a version upgrade just for this issue.

a compromise that shouldn't involve an inordinate amount of effort may be to just convert those fields to a text field for the time being. it won't be the same as the html editor that was previously there, but at least it should allow you to edit the value.
