### ISSUE TITLE
upgrade python to 3.12 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#356]
### Description/Context

The r[edwood release of open edX will be running on python 3.12](https://discuss.openedx.org/t/python-3-12-upgrade-for-tutor-and-its-plugins/12323). Can we upgrade edx-sga before the Redwood release is cut in April?

**Comment by pdpinch** [comment]
@Anas12091101 @arslanashraf7 what's involved with upgrading this repo to python 3.12?

**Comment by pdpinch** [comment]
@Anas12091101 what's the status of this?

**Comment by Anas12091101** [comment]
@pdpinch I will create a PR after https://github.com/mitodl/edx-sga/pull/355 merges. I created the branch for this issue from the `fix-integration-tests` branch and since https://github.com/mitodl/edx-sga/pull/355 is almost ready for merging, I would not have to delete the `fix-integration-tests` commits from my working branch.

**Comment by pdpinch** [comment]
@Anas12091101 can this be closed? 

Have we made a release of the version with Python 3.12 support?

**Comment by Anas12091101** [comment]
@pdpinch I think the release part is remaining. Thanks for reminding. I'll create a release on Monday.

**Comment by Anas12091101** [comment]
edx-sga v0.25.0 released : https://pypi.org/project/edx-sga/
